name: deploy-cloudrun Integration

on:
  push:
    paths:
    - 'deploy-cloudrun/**'
  pull_request:
    paths:
    - 'deploy-cloudrun/**'

jobs:
  gcloud:
    name: with setup-gcloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./setup-gcloud
      with:
        service_account_email: ${{ secrets.APPENGINE_DEPLOY_SA_EMAIL }}
        service_account_key: ${{ secrets.APPENGINE_DEPLOY_SA_KEY_B64 }}
        export_default_credentials: true
    - id: deploy
      uses: ./deploy-cloudrun
      with:
        image: gcr.io/cloudrun/hello
        service: test-hello
    - name: get output
      run: echo '${{ steps.deploy.outputs.url }}'

  b64_json:
    name: with base64 json creds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: deploy
      uses: ./deploy-cloudrun
      with:
        credentials: ${{ secrets.APPENGINE_DEPLOY_SA_KEY_B64 }}
        image: gcr.io/cloudrun/hello
        service: test-hello
    - name: get output
      run: echo '${{ steps.deploy.outputs.url }}'

  json:
    name: with json creds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: deploy
      uses: ./deploy-cloudrun
      with:
        credentials: ${{ secrets.APPENGINE_DEPLOY_SA_KEY_JSON }}
        image: gcr.io/cloudrun/hello
        service: test-hello
    - name: get output
      run: echo '${{ steps.deploy.outputs.url }}'

  envVars:
    name: with Env Vars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: deploy
      uses: ./deploy-cloudrun
      with:
        credentials: ${{ secrets.APPENGINE_DEPLOY_SA_KEY_JSON }}
        image: gcr.io/cloudrun/hello
        service: test-hello
        env_vars:
    - name: get output
      run: echo '${{ steps.deploy.outputs.url }}'

  yaml:
    name: with YAML metadata
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: deploy
      uses: ./deploy-cloudrun
      with:
        credentials: ${{ secrets.APPENGINE_DEPLOY_SA_KEY_JSON }}
        metadata: ./deploy-cloudrun/tests/service.basic.yaml
    - name: get output
      run: echo '${{ steps.deploy.outputs.url }}'

  metadata:
    name: with full YAML metada
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: deploy
      uses: ./deploy-cloudrun
      with:
        credentials: ${{ secrets.APPENGINE_DEPLOY_SA_KEY_JSON }}
        metadata: ./deploy-cloudrun/tests/service.full.yaml
    - name: get output
      run: echo '${{ steps.deploy.outputs.url }}'
