name: test

on:
  push:
    paths:
    - '.github/workflows/setup-gcloud*'

jobs:
  latest:
    name: setup-gcloud latest
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: setup-gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_key: ${{ secrets.SETUP_GCLOUD_IT_KEY }}
          project_id: ${{ secrets.DEPLOY_CLOUDRUN_PROJECT_ID }}
      - run: gcloud compute url-maps list
      - run: gcloud compute url-maps invalidate-cdn-cache test-balancer --path /* --async
